"""empty message

Revision ID: 1175e9afec06
Revises: 456eff87409
Create Date: 2014-12-15 07:46:11.999890

"""

# revision identifiers, used by Alembic.
revision = '1175e9afec06'
down_revision = '456eff87409'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices_sensors')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices_sensors',
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], [u'device.id'], name=u'devices_sensors_device_id_fkey'),
    sa.ForeignKeyConstraint(['sensor_id'], [u'sensor.id'], name=u'devices_sensors_sensor_id_fkey'),
    sa.PrimaryKeyConstraint('device_id', 'sensor_id', name=u'devices_sensors_pkey')
    )
    ### end Alembic commands ###
