"""empty message

Revision ID: 1f31c082f597
Revises: ead44476511
Create Date: 2014-12-07 22:22:49.990123

"""

# revision identifiers, used by Alembic.
revision = '1f31c082f597'
down_revision = 'ead44476511'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###
