"""empty message

Revision ID: 210d93fe7743
Revises: 5a6df40f64ac
Create Date: 2014-12-10 01:10:43.151380

"""

# revision identifiers, used by Alembic.
revision = '210d93fe7743'
down_revision = '5a6df40f64ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'device', sa.Column('device_type', sa.Integer(), nullable=True))
    op.add_column(u'device', sa.Column('location', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'device', 'device_type', ['device_type'], ['id'])
    op.drop_column(u'device', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'device', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column(u'device', 'location')
    op.drop_column(u'device', 'device_type')
    op.drop_table('device_type')
    ### end Alembic commands ###
