"""empty message

Revision ID: 2b32024710f1
Revises: 3c3b57330f7b
Create Date: 2015-06-10 01:34:43.554096

"""

# revision identifiers, used by Alembic.
revision = '2b32024710f1'
down_revision = '3c3b57330f7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        "pk_sensor", "sensor",
        ["token"]
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_sensor", "sensor", "primary")
    ### end Alembic commands ###
