"""empty message

Revision ID: 2fd34dfdef46
Revises: 391c62b861ab
Create Date: 2014-12-10 00:07:47.532401

"""

# revision identifiers, used by Alembic.
revision = '2fd34dfdef46'
down_revision = '391c62b861ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
