"""empty message

Revision ID: 35ed303a43f6
Revises: 210d93fe7743
Create Date: 2014-12-10 01:12:47.603623

"""

# revision identifiers, used by Alembic.
revision = '35ed303a43f6'
down_revision = '210d93fe7743'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
