"""empty message

Revision ID: 3c3b57330f7b
Revises: d58e0a3cbb8
Create Date: 2015-06-10 00:30:34.100500

"""

# revision identifiers, used by Alembic.
revision = '3c3b57330f7b'
down_revision = 'd58e0a3cbb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_sensor')
    op.drop_table('device_sensor')
    op.add_column('sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('sensor', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.add_column('sensor', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensor', 'environment', ['environment_id'], ['id'])
    op.create_foreign_key(None, 'sensor', 'device', ['device_id'], ['id'])
    op.create_foreign_key(None, 'sensor', 'user', ['user_id'], ['id'])
    op.drop_column('sensor', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_column('sensor', 'user_id')
    op.drop_column('sensor', 'environment_id')
    op.drop_column('sensor', 'device_id')
    op.create_table('device_sensor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], [u'device.id'], name=u'device_sensor_device_id_fkey'),
    sa.ForeignKeyConstraint(['sensor_id'], [u'sensor.id'], name=u'device_sensor_sensor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'device_sensor_pkey')
    )
    op.create_table('environment_sensor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('environment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sensor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], [u'environment.id'], name=u'environment_sensor_environment_id_fkey'),
    sa.ForeignKeyConstraint(['sensor_id'], [u'sensor.id'], name=u'environment_sensor_sensor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'environment_sensor_pkey')
    )
    ### end Alembic commands ###
