"""update project model

Revision ID: 4044ab2fae9b
Revises: 1b954f2c765
Create Date: 2015-03-14 14:56:42.488263

"""

# revision identifiers, used by Alembic.
revision = '4044ab2fae9b'
down_revision = '1b954f2c765'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('budget', sa.String(length=80), nullable=True))
    op.add_column('project', sa.Column('email', sa.String(length=80), nullable=True))
    op.drop_constraint(u'project_project_category_id_fkey', 'project', type_='foreignkey')
    op.drop_constraint(u'project_user_id_fkey', 'project', type_='foreignkey')
    op.drop_constraint(u'project_project_budget_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'skills')
    op.drop_column('project', 'project_category_id')
    op.drop_column('project', 'user_id')
    op.drop_column('project', 'project_budget_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_budget_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('project_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('skills', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_foreign_key(u'project_project_budget_id_fkey', 'project', 'project_budget', ['project_budget_id'], ['id'])
    op.create_foreign_key(u'project_user_id_fkey', 'project', 'user', ['user_id'], ['id'])
    op.create_foreign_key(u'project_project_category_id_fkey', 'project', 'project_category', ['project_category_id'], ['id'])
    op.drop_column('project', 'email')
    op.drop_column('project', 'budget')
    ### end Alembic commands ###
