"""empty message

Revision ID: 456eff87409
Revises: 572ca0eea416
Create Date: 2014-12-15 07:44:41.226958

"""

# revision identifiers, used by Alembic.
revision = '456eff87409'
down_revision = '5720f7c8cd8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('sensor', sa.Column('token', sa.String(length=80), nullable=True))
    op.create_foreign_key(None, 'sensor', 'device', ['device_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_column('sensor', 'token')
    op.drop_column('sensor', 'device_id')
    ### end Alembic commands ###
