"""empty message

Revision ID: 4eb1efd14c83
Revises: 55511fe4e325
Create Date: 2015-04-25 13:06:15.022695

"""

# revision identifiers, used by Alembic.
revision = '4eb1efd14c83'
down_revision = '55511fe4e325'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('environment_type_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_type_id'], ['environment_type.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'device', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'environment', ['environment_id'], ['id'])
    op.drop_column(u'device', 'location')
    op.add_column(u'sensor', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.add_column(u'sensor', sa.Column('sensor_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensor', 'sensor_type', ['sensor_type_id'], ['id'])
    op.create_foreign_key(None, 'sensor', 'environment', ['environment_id'], ['id'])
    op.drop_column(u'sensor', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'sensor', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_column(u'sensor', 'sensor_type_id')
    op.drop_column(u'sensor', 'environment_id')
    op.add_column(u'device', sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column(u'device', 'environment_id')
    op.drop_table('environment')
    op.drop_table('sensor_type')
    op.drop_table('environment_type')
    ### end Alembic commands ###
