"""drop project_category and project_budget

Revision ID: 55511fe4e325
Revises: 4044ab2fae9b
Create Date: 2015-03-14 15:33:25.338608

"""

# revision identifiers, used by Alembic.
revision = '55511fe4e325'
down_revision = '4044ab2fae9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_category')
    op.drop_table('project_budget')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_budget',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'project_budget_pkey')
    )
    op.create_table('project_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'project_category_pkey')
    )
    ### end Alembic commands ###
