"""empty message

Revision ID: 5720f7c8cd8a
Revises: 35ed303a43f6
Create Date: 2014-12-10 01:17:39.886331

"""

# revision identifiers, used by Alembic.
revision = '5720f7c8cd8a'
down_revision = '35ed303a43f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_type_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'device_device_type_fkey', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'device_type', ['device_type_id'], ['id'])
    op.drop_column('device', 'device_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key(u'device_device_type_fkey', 'device', 'device_type', ['device_type'], ['id'])
    op.drop_column('device', 'device_type_id')
    ### end Alembic commands ###
