"""empty message

Revision ID: 572ca0eea416
Revises: 5720f7c8cd8a
Create Date: 2014-12-14 13:39:47.754699

"""

# revision identifiers, used by Alembic.
revision = '572ca0eea416'
down_revision = '5720f7c8cd8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
