"""empty message

Revision ID: 5a6df40f64ac
Revises: 15d1e5037bba
Create Date: 2014-12-10 00:55:27.357426

"""

# revision identifiers, used by Alembic.
revision = '5a6df40f64ac'
down_revision = '15d1e5037bba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('merk', sa.String(length=80), nullable=True))
    op.add_column('device', sa.Column('type', sa.String(length=80), nullable=True))
    op.add_column('device', sa.Column('wattage', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'wattage')
    op.drop_column('device', 'type')
    op.drop_column('device', 'merk')
    ### end Alembic commands ###
